CREATE TABLE Sensor (
    SensorId INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Status NVARCHAR(20) NOT NULL
);

CREATE TABLE AdminUser (
    AdminUserId INT IDENTITY PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    PasswordHash NVARCHAR(256) NOT NULL,
    Email NVARCHAR(100) NOT NULL
);

CREATE TABLE SensorData (
    SensorDataId INT IDENTITY PRIMARY KEY,
    SensorId INT FOREIGN KEY REFERENCES Sensor(SensorId) ON DELETE CASCADE,
    Timestamp DATETIME NOT NULL,
    AQI INT NOT NULL
);

CREATE TABLE SimulationSettings (
    SimulationSettingsId INT PRIMARY KEY DEFAULT 1,
    Enabled BIT NOT NULL DEFAULT 1,
    IntervalSeconds INT NOT NULL DEFAULT 30
);